### ISSUE TITLE
ng build prod: TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by oren-said** [taldor-ltd/tld-angular-fnd#13]
get to this error when ng build --prod
vesion: 1.0.0
angular/cli:  8.3.25

**Comment by benshabatnoam** [comment]
Hello oren,

I'm not getting this error on build prod.

Can you please upload project files:

- `package.json`
- `angular.json`

Thanks

**Comment by benshabatnoam** [comment]
> Files from oren
<sub>[View in Slack](https://taldordev.slack.com/archives/DT8U74K96/p1583226797000100)</sub>

**Comment by benshabatnoam** [comment]
Oren, this error comes from the angular optimizer package.

It's not a problem in this repo!

Update this package in your project in order to fix this error, follow this steps:

1. Run this command:
`npm un @angular-devkit/build-angular`

2. Run this command:
`npm i @angular-devkit/build-angular@0.803.21 --save-dev`
